### ISSUE TITLE
[Enhancement] add line & column numbers to parser error messages (fix included)

### ISSUE THREAD

**Issue by rozek** [bigskysoftware/_hyperscript#404]
Could one please decorate parser error messages with line & column numbers? It is not very helpful to get messages like

```
_hyperscript.min.js:1 hyperscript errors were found on the following element: <script type=​"text/​hyperscript">​…​</script>​ 

 Unexpected Token : in

    end
                              ^^

 Error: Unexpected Token : in

    end
                              ^^


    at a.raiseParseError (https://127.0.0.1:7443/js/_hyperscript.min.js:1:11879)
    at a.raiseParseError (https://127.0.0.1:7443/js/_hyperscript.min.js:1:11937)
    at a.parseHyperScript (https://127.0.0.1:7443/js/_hyperscript.min.js:1:12039)
    at o.initElement (https://127.0.0.1:7443/js/_hyperscript.min.js:1:18879)
    at https://127.0.0.1:7443/js/_hyperscript.min.js:1:18542
    at o.forEach (https://127.0.0.1:7443/js/_hyperscript.min.js:1:14092)
    at o.processNode (https://127.0.0.1:7443/js/_hyperscript.min.js:1:18472)
    at HTMLDocument.<anonymous> (https://127.0.0.1:7443/js/_hyperscript.min.js:1:95689)
```

as this requires unnecessary work to locate the problem

**Comment by rozek** [comment]
The change might be simple: in _hyperscript.ts, just change line 1234 ("return" from "createParserContext") to

```
          return (
            contextLine + "\n" + 
            "found in line " + (line+1) + " at column " + (offset+1) + "\n" +
            " ".repeat(offset) + "^^\n\n"
          );
```

or similar

**Comment by rozek** [comment]
just a small note: the logged line number seems to be too small (when compared with the source), although I do not know why...
